### ISSUE TITLE
[Docs] add full example for using shell provider

### ISSUE THREAD

**Issue by jackmac92** [ikalnytskyi/httpie-credential-store#21]
Hey having trouble figuring out how to use the shell token provider, not sure what I'm missing

I'd like to use a shell command to grab the token, and apply that as a header value with a custom key. Is that possible?

**Comment by ikalnytskyi** [comment]
Hey @jackmac92,

The credential definition should look like this:

```json
[
  {
    "url": "api.github.com",
    "auth": {
      "provider": "header",
      "name": "X-My-Custom-Header-Name",
      "value": {
        "keychain": "shell",
        "command": "cat ~/path/to/secret | tr -d '\n'"
      }
    }
  }
]

```

**Comment by jackmac92** [comment]
thanks this is very useful!!
